global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'temporalmetrics'
    metrics_path: /metrics
    scheme: http
    static_configs:
      # Cluster metrics target
      - targets:
          - 'host.docker.internal:9091'
        labels:
          group: 'server-metrics'